Cleanup old zsh-config and make it all snazzy

diff --git a/functions/cheat b/functions/cheat
--- a/functions/cheat
+++ b/functions/cheat
@@ -1,34 +1,71 @@
 #!/usr/bin/env zsh
 
 function cheat() {
-  if [[ -z "$CHEATSHEET_DIR" ]]; then
-    echo "CHEATSHEET_DIR not set, set it before running this script"
+  if is equal "$1" "--help"; then
+    echo "$c[h1]Cheatsheets by glow$c[reset]"
+    echo ""
+    echo "$c[h2]Usage:$c[reset]"
+    echo "cheat $c[flag][--help]$c[reset] show this help message"
+    echo ""
+    echo "$c[h3]List all cheatsheets$c[reset]"
+    echo "cheat $c[flag]--list$c[reset]"
+    echo ""
+    echo "$c[h3]show all cheatsheets$c[reset]"
+    echo "cheat"
+    echo "cheat $c[flag][glow-args]$c[reset]"
+    echo ""
+    echo "$c[h3]show specific cheatsheet$c[reset]"
+    echo "cheat $c[param]sheet-name$c[reset] $c[flag][glow-args]$c[reset]"
+    echo ""
+    echo "$c[h3]edit specific cheatsheet$c[reset]"
+    echo "cheat $c[param]sheet-name$c[reset] $c[flag]--edit$c[reset]"
+    echo ""
+    return 0
+  fi
+
+  if is empty "$CHEATSHEET_DIR"; then
+    echo "CHEATSHEET_DIR not set, run zsh-config/install to install it"
     return 1
   fi
 
-  if ! command -v glow > /dev/null 2>&1; then
-    echo "glow could not be found, please install it before running this script"
+  if is not available glow; then
+    echo "glow could not be found, run zsh-config/install to install it"
     return 1
   fi
 
-  if [[ "$1" != "" ]]; then
-    local sheet_name
-    sheet_name="${1%.md}"
+  if is empty "$1"; then
+    glow "$CHEATSHEET_DIR"
+    return $?
+  fi
 
-    if [[ -f "$CHEATSHEET_DIR/$sheet_name.md" ]]; then
-      local -a other_args
-      other_args=("${(@)argv[2,-1]}")
-      if [[ ${#other_args} -gt 0 ]]; then
-        glow "$CHEATSHEET_DIR/$sheet_name.md" "${other_args[@]}"
-      else
-        glow "$CHEATSHEET_DIR/$sheet_name.md"
-      fi
-    else
-      glow "$CHEATSHEET_DIR" "$@"
-    fi
-  else
+  if is equal "$1" "--list"; then
+    echo "$c[h1]Available Cheatsheets:$c[reset]"
+    ls -1 "$CHEATSHEET_DIR" | grep -v '.DS_Store' | sed 's/\.md$//'
+    return $?
+  fi
+
+  local sheet_name
+  sheet_name="${1%.md}"
+
+  if is not file "$CHEATSHEET_DIR/$sheet_name.md"; then
     glow "$CHEATSHEET_DIR" "$@"
+    return $?
   fi
+
+  local -a other_args
+  other_args=("${(@)argv[2,-1]}")
+  if is equal "${#other_args}" "0"; then
+    glow "$CHEATSHEET_DIR/$sheet_name.md"
+    return $?
+  fi
+
+  if is equal "$other_args[1]" "--edit"; then
+    micro "$CHEATSHEET_DIR/$sheet_name.md"
+    return $?
+  fi
+
+  glow "$CHEATSHEET_DIR/$sheet_name.md" "${other_args[@]}"
+  return $?
 }
 
 cheat "$@"
diff --git a/functions/gcod b/functions/gcod
--- a/functions/gcod
+++ b/functions/gcod
@@ -3,7 +3,6 @@
 # gcod: Checks out development (git flow configured)
 function gcod () {
   local DEPS=(
-    is
     git
   )
 
@@ -13,12 +12,16 @@ function gcod () {
 
   DEV_BRANCH=$(git config gitflow.branch.develop)
   if is empty "$DEV_BRANCH"; then
-    echo "$cs[error]Could not get develop branch\n$c[reset]"
-    echo "$cs[sub]Make sure you are in a git repo and then run:$c[reset] git flow init"
     return 1
   fi
 
   git checkout $DEV_BRANCH
+    if is not equal "$?" "0"; then
+    echo "$c[error]Could not checkout development branch ($DEV_BRANCH)\n$c[reset]"
+    echo "$c[sub]to set the development branch for this repo:$c[reset]"
+    echo "git config gitflow.branch.develop $c[flag]develop$c[reset]"
+    return 1
+  fi
 }
 
 gcod "$@"
diff --git a/functions/gcom b/functions/gcom
--- a/functions/gcom
+++ b/functions/gcom
@@ -1,9 +1,8 @@
 #!/usr/bin/env zsh
 
-# gcom: Checks out master (git flow configured)
+# gcom: Checks out main
 function gcom () {
   local DEPS=(
-    is
     git
   )
 
@@ -11,15 +10,18 @@ function gcom () {
     return
   fi
 
-  MASTER_BRANCH=$(git config gitflow.branch.master)
-  if is empty "$MASTER_BRANCH"; then
-    MASTER_BRANCH=main
-    # echo "$cs[error]Could not get master branch$c[reset]"
-    # echo "$cs[sub]Make sure you are in a git repo and then run:$c[reset] git flow init"
-    # return 1
+  MAIN_BRANCH=$(git config gitflow.branch.main)
+  if is empty "$MAIN_BRANCH"; then
+    MAIN_BRANCH=main
   fi
 
-  git checkout $MASTER_BRANCH
+  git checkout $MAIN_BRANCH
+  if is not equal "$?" "0"; then
+    echo "$c[error]Could not checkout main branch ($MAIN_BRANCH)\n$c[reset]"
+    echo "$c[sub]to set the main branch for this repo:$c[reset]"
+    echo "git config gitflow.branch.main $c[flag]main$c[reset]"
+    return 1
+  fi
 }
 
 gcom "$@"
diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,44 +1,37 @@
 #!/usr/bin/env zsh
 
-# The directory this install script runs from
-SOURCE_DIR=${0:a:h}
+source "${0:a:h}/installers/_stub"
 
-if [[ -z "$HOME" ]]; then
-  echo '$HOME not set, set it before running this script'
-  exit 1
+if is equal "$1" "--help"; then
+  echo "$c[h1]Install Everything$c[reset]"
+  echo "$c[lead]requires zsh, and \$HOME to be set$c[reset]"
+  echo ""
+  echo "$c[info-small]Shell:$c[reset] $SHELL"
+  echo "$c[info-small]HOME:$c[reset] $HOME"
+  echo ""
+  echo "$c[h2]Usage:$c[reset]"
+  echo "install $c[flag][--help]$c[reset]"
+  exit 0
 fi
 
-source ./functions/is
+SCRIPTS=$(ls -1 $INSTALLER_DIR | grep -v '.DS_Store' | grep -v '^_' 2> /dev/null)
 
-# Expected destination
-DEST_DIR=$HOME/.custom
-DEST_ZSHRC=$HOME/.zshrc
-DEST_ZSHENV=$HOME/.zshenv
+for script in ${(f)SCRIPTS}; do
+  [[ -z "$script" ]] && continue
+  echo "$c[info]running installer$c[reset] $script"
+  if is not executable "$INSTALLER_DIR/$script"; then
+    echo "$c[warn]warning:$c[reset] $script is not executable, making it executable"
+    chmod +x "$INSTALLER_DIR/$script"
+  fi
 
-echo 'Linking zsh-config:'
-echo "From: $SOURCE_DIR"
-echo "To: $DEST_DIR"
-echo "linking .zshrc to: $DEST_ZSHRC"
-echo "linking .zshenv to: $DEST_ZSHENV"
+  "$INSTALLER_DIR/$script"
 
-# Clean old instances if they exist
-if [[ -h $DEST_DIR ]]; then
-  rm $DEST_DIR
-fi
-
-if [[ -h $DEST_ZSHRC ]]; then
-  rm $DEST_ZSHRC
-fi
-
-if [[ -h $DEST_ZSHENV ]]; then
-  rm $DEST_ZSHENV
-fi
-
-if [[ -h $HOME/.default-python-packages ]]; then
-  rm $HOME/.default-python-packages
-fi
-
-sudo ln -s $SOURCE_DIR $DEST_DIR
-sudo ln -s $DEST_DIR/.zshrc $DEST_ZSHRC
-sudo ln -s $DEST_DIR/.zshenv $DEST_ZSHENV
-sudo ln -s $DEST_DIR/.default-python-packages $HOME/.default-python-packages
+  if is equal "$?" "0"; then
+    echo "$c[success]succesfully ran$c[reset] $script"
+  else
+    echo "$c[error]failed$c[reset] $script"
+    exit 1
+  fi
+  echo ""
+  echo ""
+done
