color rider

diff --git a/functions/rider b/functions/rider
--- a/functions/rider
+++ b/functions/rider
@@ -1,16 +1,12 @@
 #!/usr/bin/env zsh
 
-# alias wso='open -na "WebStorm.app" --args "$(pwd)"'
-
-# ls -1 | grep 'WebStorm'
-
 function _rider_find_sln() {
   SLN=$(ls -1 | grep .sln | head -1)
   PROJ=$(ls -1 | grep .csproj | head -1)
 
   if is empty "$SLN"; then
     if is empty "$PROJ"; then
-      clr_red ".sln/.csproj not found, try passing it as an argument"
+      echo ".sln/.csproj $cs[error]not found in current directory.$c[red]"
       return 1
     fi
 
@@ -19,26 +15,23 @@ function _rider_find_sln() {
   fi
 
   open -na "/Applications/Rider.app" --args "$SLN"
+  return 0
 }
 
 # Webstorm Open Here
 function rider () {
   local DEPS=(
     is
-    clr_cyan
-    clr_green
-    clr_white
-    clr_red
   )
 
   if is not existing "/Applications/Rider.app"; then
-    clr_red "Rider not installed";
-    return 1;
+    echo "$cs[error]Rider not installed$c[reset]";
+    return 1
   fi
 
   if is equal "$1" "."; then
     _rider_find_sln
-    return 0;
+    return $?
   fi
 
   open -na "/Applications/Rider.app" --args "$@"
