color help sim

diff --git a/functions/sim b/functions/sim
--- a/functions/sim
+++ b/functions/sim
@@ -1,68 +1,48 @@
 #!/usr/bin/env zsh
 
-function _abspath() {
-    if [[ -d "$1" ]]; then
-        # dir
-        (cd "$1"; pwd)
-    elif [[ -f "$1" ]]; then
-        # file
-        if [[ $1 == */* ]]; then
-            return "$(cd "${1%/*}"; pwd)/${1##*/}"
-        else
-            return "$(pwd)/$1"
-        fi
-    fi
-}
-
-function _sim_usage() {
-  clr_cyan 'Works with the running simulator'
-  clr_cyan 'Usage:' -n
-  clr_white " $1 command\n"
-
-  clr_cyan 'Commands:'
-  clr_green 'set-clock 10:00' -n
-  clr_white '\t\t- Sets the clock time to the given time'
-  clr_green 'screenshot path.png' -n
-  clr_white '\t- Takes a screenshot and saves it to path'
-  clr_green 'screenrecord path.mov' -n
-  clr_white '\t- Takes a screen recording and saves it to path'
-  clr_green 'install path.app' -n
-  clr_white '\t- Installs App from path on the current sim'
-
-}
+_sim_description="Manages the running iOS simulator"
+_sim_positional=""
+_sim_positional_desc=""
+_sim_flag_names[1]="--help"
+_sim_flag_messages[1]="shows help"
+_sim_flag_names[2]="--set-clock [time]"
+_sim_flag_messages[2]="Sets the clock to [time] e.g. 10:00"
+_sim_flag_names[3]="--screenshot [path]"
+_sim_flag_messages[3]="Saves a screenshot to [path] (.png)"
+_sim_flag_names[4]="--screen-record [path]"
+_sim_flag_messages[4]="Starts screen recording to [path] (.mov)"
+_sim_flag_names[5]="--install [path]"
+_sim_flag_messages[5]="Installs the app at [path] (.app)"
+_sim_flag_names[6]="--logs"
+_sim_flag_messages[6]="Prints the simulator's logs"
 
 function _sim_install() {
-  self_command=$1
+  APP="$1"
 
-  if is empty "$2"; then
-    clr_red "No app passed to command"
-    _gcmm_usage $self_command;
-    return 1;
-  fi;
+  if is empty "$APP"; then
+    echo "$cs[error]No app to install, see --help for usage.$c[reset]"
+    return 1
+  fi
 
-  xcrun simctl install booted "$2"
+  xcrun simctl install booted "$APP"
 }
 
 function _sim_set_clock() {
-  self_command=$1
+  TIME=$1
+  if is empty "$TIME"; then
+    echo "$cs[error]No time to set, see --help for usage.$c[reset]"
+    return 1
+  fi
 
-  if is empty "$2"; then
-    clr_red "No time passed to command"
-    _gcmm_usage $self_command;
-    return 1;
-  fi;
-
-  xcrun simctl status_bar booted override --time "$2" --batteryState charged --batteryLevel 100
+  xcrun simctl status_bar booted override --time "$TIME" --batteryState charged --batteryLevel 100
 }
 
 function _sim_screenshot() {
-  self_command=$1
-
-  if is empty "$2"; then
-    clr_red "No path passed to command"
-    _gcmm_usage $self_command;
-    return 1;
-  fi;
+  SS_PATH=$1
+  if is empty "$SS_PATH"; then
+    echo "$cs[error]No path to save screenshot to, see --help for usage.$c[reset]"
+    return 1
+  fi
 
   folderpath=${2%/*}
   if is not empty "$folderpath"; then
@@ -71,21 +51,19 @@ function _sim_screenshot() {
 
   xcrun simctl io booted screenshot "$2" &>/dev/null
   if is not equal "$?" "0"; then
-    clr_red "Could not capture screenshot, try running manually:"
-    clr_red "xcrun simctl io booted screenshot \"$2\""
+    echo "$cs[error]Could not capture screenshot. Try running:.$c[reset]"
+    echo "xcrun simctl io booted screenshot \"$2\""
     return 1
   fi
 
-  clr_green "Captured $2"
+  echo "$cs[success]Captured$c[reset] $2"
 }
 
 function _sim_screenrecord() {
-  self_command=$1
-
-  if is empty "$2"; then
-    clr_red "No path passed to command"
-    _gcmm_usage $self_command;
-    return 1;
+  SR_PATH="$1"
+  if is empty "$SR_PATH"; then
+    echo "$cs[error]No path to save screen recording to, see --help for usage.$c[reset]"
+    return 1
   fi;
 
   folderpath=${2%/*}
@@ -95,8 +73,8 @@ function _sim_screenrecord() {
 
   # xcrun simctl io booted recordVideo "$2"
   # if is not equal "$?" "0"; then
-    clr_red "Could not capture screen recording, try running manually:"
-    clr_red "xcrun simctl io booted recordVideo \"$2\""
+    echo "$cs[error]Could not capture screen recording. Try running:.$c[reset]"
+    echo "xcrun simctl io booted recordVideo \"$2\""
     return 1
   # fi
 
@@ -122,34 +100,39 @@ function sim () {
     return
   fi
 
-  if is empty "$1"; then
-    _sim_usage $0
+  if is empty "$1" || has-flag '--help' $@; then
+    print-help \
+      "$0" \
+      "$_sim_description" \
+      "_sim_flag_names" \
+      "_sim_flag_messages" \
+      "$_sim_positional" \
+      "$_sim_positional_desc"
     return 0
   fi
 
-  if is equal "$1" "set-clock"; then
-    _sim_set_clock $0 $2
-    return 0;
+  if has-flag '--set-clock' $@; then
+    _sim_set_clock $(flag-value '--set-clock' $@)
+    return $?
+  fi
+  if has-flag '--screenshot' $@; then
+    _sim_screenshot  $(flag-value '--screenshot' $@)
+    return $?
   fi
 
-  if is equal "$1" "screenshot"; then
-    _sim_screenshot $0 $2
-    return 0;
+  if has-flag '--screen-record' $@; then
+    _sim_screenrecord $(flag-value '--screen-record' $@)
+    return $?
   fi
 
-  if is equal "$1" "screenrecord"; then
-    _sim_screenrecord $0 $2
-    return 0;
+  if has-flag '--install' $@; then
+    _sim_install $(flag-value '--install' $@)
+    return $?
   fi
 
-  if is equal "$1" "install"; then
-    _sim_install $0 $2
-    return 0;
-  fi
-
-  if is equal "$1" "logs"; then
+  if has-flag '--logs' $@; then
     _sim_logs
-    return 0;
+    return $?
   fi
 
 }
